site_name: 'Computer Science Note'
site_url: 'https://kaienlin.github.io/CS-note/'

repo_name: 'kaienlin/CS-note/'
repo_url: 'https://github.com/kaienlin/CS-note/'

theme:
    name: 'material'
    logo:
        icon: 'code'
    palette:
        primary: 'white'
        accent: 'light blue'
    feature:
        tabs: true

nav:
    - Home: 'index.md'
    - About: 'about/index.md'
    - Algorithms: 'algorithms/index.md'
    - Courses: 'courses/index.md'
    - Miscellaneous: 'misc/index.md'

plugins:
    - search
    - macros

markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - codehilite
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

# extra_css:
#    - 'css/syntax_highlight.css'

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/kaienlin'
      
